version: '3'

services:
  db:
    image: mysql
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - lo-era
    volumes:
      - db_volume:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/config/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lo-era
      time_zone: UTC

volumes:
  db_volume:

networks:
  lo-era:
    external: true
