name: Deploy

on:
  workflow_dispatch:

env:
  DOCKER_NAME: lo-era-auth
  DOCKER_IMAGE: ghcr.io/heavyrisem/lo-era-auth

jobs:
  deploy:
    runs-on: [self-hosted, deploy]

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Get Pushed Tags Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Deploy
        run: |
          docker stack deploy -c docker-deploy.yml ${{ env.DOCKER_NAME }}

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: |
      #       ${{ env.DOCKER_IMAGE }}:${{ env.RELEASE_VERSION }}
      #       ${{ env.DOCKER_IMAGE }}:latest
