name: Build And Push

on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_NAME: lo-era-auth
  DOCKER_IMAGE: ghcr.io/heavyrisem/lo-era-auth

jobs:
  build-push:
    runs-on: [self-hosted, build]

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Pushed Tags Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.RELEASE_VERSION }}
            ${{ env.DOCKER_IMAGE }}:latest
